Repository appuio/terraform-openshift4-exoscale, pull requests merged in 2021-11, with the labels that each got.

#34 Allow passing team for LBaaS
  lb.tf
  templates/hieradata.yaml.tmpl
  variables.tf
Labels: enhancement

#35 Set puppet environment to `AppuioLbaas`
  lb.tf
Labels: bug

#36 Ignore changes in LB user-data after creation
  lb.tf
Labels: change

#37 Introduce separate variable `cluster_name`
  README.md
  bootstrap.tf
  control_plane.tf
  infra.tf
  lb.tf
  main.tf
  modules/node-group/main.tf
  modules/node-group/variables.tf
  output.tf
  storage.tf
  variables.tf
  worker.tf
Labels: enhancement
