Repository appuio/terraform-openshift4-exoscale, pull requests merged in 2022-10, with the labels that each got.

#62 Fix variable description for `additional_lb_networks`
  variables.tf
Labels: documentation

#63 Remove unused DNS records
  bootstrap.tf
  infra.tf
Labels: change

#66 Update minimum required Terraform version to 1.3.0 in `node-group` module
  modules/node-group/providers.tf
Labels: breaking

#65 Use `exoscale_domain.<name>.id` to associate `exoscale_domain_record` resources with their domain
  main.tf
Labels: bug

#67 Fix validation logic for `additional_node_groups.*.state`
  variables.tf
Labels: bug

#68 Pin Exoscale Terraform provider version to 0.41.0
  modules/node-group/providers.tf
  provider.tf
Labels: dependency

#60 Remove all uses of deprecated Exoscale Terraform resources
  bootstrap.tf
  control_plane.tf
  infra.tf
  main.tf
  modules/node-group/main.tf
  modules/node-group/output.tf
  modules/node-group/variables.tf
  security_groups.tf
  storage.tf
  variables.tf
  worker.tf
Labels: breaking

#71 Add support for configuring deployment target ID
  README.md
  control_plane.tf
  infra.tf
  lb.tf
  modules/node-group/main.tf
  modules/node-group/variables.tf
  storage.tf
  variables.tf
  worker.tf
Labels: enhancement
